---
title: "Forest Fire Project Part 2"
author: "Shi Fan Jin"
date: "11/7/2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MASS)
library(dplyr)
set.seed(1)
```

```{r}
forest = read.csv("forestfires.csv", stringsAsFactors = FALSE)
```


#Transform the data
###Transform the "area" using log(x + 1), "FFMC" with log(x), and remove rain.
###In order to make it easier to see (spread it out)
```{r}
table(forest$rain)
barplot(table(forest$rain), main = "rain freq")
## Most of the fire happens when there's no rain
## In this case, Let's remove "rain" for this practice
forest = forest[, -12]

# Transform the data
forest$area = log(forest$area + 1)
forest$FFMC = log(forest$FFMC)
#forest$ISI = log(forest$ISI)
```

###Transform the "month" and "day" into numeric values
```{r}
########## CHANGING month and day into numeric values
for (i in 1:517) {
  
  if(forest$month[i] == "jan") {
    forest$month[i] = 1
  }else if (forest$month[i] == "feb") {
    forest$month[i] = 2
  }else if (forest$month[i] == "mar") {
    forest$month[i] = 3
  }else if (forest$month[i] == "apr") {
    forest$month[i] = 4
  }else if (forest$month[i] == "may") {
    forest$month[i] = 5
  }else if (forest$month[i] == "jun") {
    forest$month[i] = 6
  }else if (forest$month[i] == "jul") {
    forest$month[i] = 7
  }else if (forest$month[i] == "aug") {
    forest$month[i] = 8
  }else if (forest$month[i] == "sep") {
    forest$month[i] = 9
  }else if (forest$month[i] == "oct") {
    forest$month[i] = 10
  }else if (forest$month[i] == "nov") {
    forest$month[i] = 11
  }else if (forest$month[i] == "dec") {
    forest$month[i] = 12
  }
  
  if (forest$day[i] == "mon") {
    forest$day[i] = 1
  } else if (forest$day[i] == "tue") {
    forest$day[i] = 2
  } else if (forest$day[i] == "wed") {
    forest$day[i] = 3
  } else if (forest$day[i] == "thu") {
    forest$day[i] = 4
  } else if (forest$day[i] == "fri") {
    forest$day[i] = 5
  } else if (forest$day[i] == "sat") {
    forest$day[i] = 6
  } else if (forest$day[i] == "sun") {
    forest$day[i] = 7
  }
}

class(forest$month[157])
class(forest$day[157])

forest$month = as.numeric(forest$month)
forest$day = as.numeric(forest$day)

cor(forest)
# FOR PREDICTING "AREA"
#'temp' has the highest correlation with the area of forest fire(which is a positive correlation), followed by 'RH' also a positive correlation, 'Rain' has the least correlation
```

#Topic 1. Model Selection
##Split data into 2/3 as training set and 1/3 as the test set
```{r}
train_size = floor((length(forest$X)/3) * 2)
train = sample(517, train_size)
test_size = length(forest$X) - train

trainset = forest[train, ]
testset = forest[-train, ]
```

## Forward and Backward Selection (NEW)
```{r}
glm.fits_new1 = glm(area~ X + month + day + FFMC + DMC + DC + ISI + temp + RH + wind, data = trainset)
```






## Forward and Backward Selection (OLD)
```{r}
# Let's make a model
#lm.fit = lm(area~ X + Y + month + day + FFMC + DMC + DC + ISI + temp + RH + wind, data = forest)
#glm.fits = glm(area~ ., data = trainset)
glm.fits = glm(area~ X + Y + month + day + FFMC + DMC + DC + ISI + temp + RH + wind, data = trainset)
# Let's try forward and backward selection to figure out which variable have more significant effect on causing a fire.

###################Backward
backwards=step(glm.fits)
# OUTPUT: area ~ X + month + DMC + DC + ISI + temp
# with the lowest AIC = 1214.32
summary(backwards)
###################Forward
nothing = glm(area~ 1, data = trainset)
forwards = step(nothing, 
                scope = list(lower = formula(nothing), 
                             upper = formula(glm.fits)), direction = "forward")
# OUTPUT: area ~ month + Y
# with the lowest AIC = 1214.44
summary(forwards)
###################Use CV to see which model is better
###################Applied the trained model (both backward and forward) to the test-data to compare the error
pred_back = predict(backwards, testset)
mean((pred_back - testset$area)^2)

pred_forward = predict(forwards, testset)
mean((pred_forward - testset$area)^2)

###Looks like forward selection model is better, since the MSE is lower (1.872752 < 1.886026)

```






```{r}
###################################TRANSFORMING >>> "fire"
# Since the 13th column indicates the burned area, if there isn't fire, the area = 0. In this case, we can transform this variable into whether or not there is a forest fire.
fire = rep(0, length(forest$X))
forest = cbind(forest, fire)
for (i in 1:length(forest$area)) {
  if (forest$area[i] > 0) {
    forest$fire[i] = 1
  }
}
# In this case, if fire = 0, there is no fire, if fire = 1, there is a fire.


###################################FINDING MODEL
# Let's make a model (excluding month, day, since they are not numeric):
glm.fits = glm(fire~ X + Y + FFMC + DMC + DC + ISI + temp + RH + wind + area, data = forest)
# Let's try forward and backward selection to figure out which variable have more significant effect on causing a fire.
###################Backward
backwards=step(glm.fits)
# OUTPUT: fire ~ Y + DC + wind + area 
# with the lowest AIC = 732.78
###################Forward
nothing = glm(fire~ 1, data = forest)
forwards = step(nothing, 
                scope = list(lower = formula(nothing), 
                             upper = formula(glm.fits)), direction = "forward")
# OUTPUT: fire ~ area + DC + wind + Y
# with the lowest AIC = 732.78
######### lOOKS LIKE BOTH BACKWARD AND FORWARD SUGGESTS THE SAME MODEL: fire ~ Y + DC + wind + area 
glm.selected = glm(fire ~ area + DC + wind + Y, data = forest)
summary(glm.selected)
```


```{r}
plot(forest$area, forest$fire)
plot(forest$DC, forest$fire)
plot(forest$wind, forest$fire)
plot(forest$Y, forest$fire)

#################USE linear discriminant analysis
#######################USE SVM???
########################################USE TREE TO SEE HOW TO CLASSIFY AS SMALL FIRE, MEDIUM FIRE, BIG FIRE?

```

```{r}
#randomly divide the dataset to make training set and testing set to see if our model is good or not
train = sample(length(forest$X), size = 450)
trainset = forest[train,]
testset = forest[-train,]
dim(trainset)
dim(testset)


lda.fit = lda(fire~ area + DC + wind + Y, data = trainset)
lda.fit
plot(lda.fit)
```


#CLOSER LOOK AT EACH VARIABLES
```{r}
##########PICK THE FIRE ONES OUT FIRST

table(forest$X)
barplot(table(forest$X), main = "X freq")
## Even number? ## No clear differentiation

table(forest$Y)
barplot(table(forest$Y), main = "Y freq")
## Seems like most of the fire occurs in the location where Y = 4 (5)

table(forest$month)
barplot(table(forest$month), main = "month freq")
## Most of the fire happens in August and September

table(forest$day)
barplot(table(forest$day), main = "day freq")
## No clear differentiation

table(forest$FFMC)
barplot(table(forest$FFMC), main = "FFMC freq")
## Left Skewed histogram

table(forest$DMC)
barplot(table(forest$DMC), main = "DMC freq")
## No clear differentiation

table(forest$DC)
barplot(table(forest$DC), main = "DC freq")
## No clear differentiation

table(forest$ISI)
barplot(table(forest$ISI), main = "ISI freq")
## No clear differentiation

table(forest$temp)
barplot(table(forest$temp), main = "temp freq")
## No clear differentiation

table(forest$RH)
barplot(table(forest$RH), main = "RH freq")
## Right Skewed histogram

table(forest$wind)
barplot(table(forest$wind), main = "wind freq")
## Right Skewed histogram

table(forest$rain)
# barplot(table(forest$rain), main = "rain freq")
## Most of the fire happens when there's no rain

table(forest$area)
barplot(table(forest$area), main = "area freq")
## No clear differentiation
### THIS IS A RESULT OF FIRE
```




