---
title: "Forest Fire Project Part 1"
author: "Shi Fan Jin, Esther Law, Changning Liu"
date: "November 23, 2018"
output: pdf_document
---

```{r,message=FALSE,include=FALSE}
library(readr)
#library(DataComputing)
library(glmnet)
library(tree)
library(boot)
library(class)
library(randomForest)
library(corrplot)
library(boot)
data=read_csv("forestfires.csv")
set.seed(1)
```

```{r}
#clean dataset
par(mfrow=c(1,2))
hist(data$area)
hist(data$FFMC)
data$area=log(data$area+1)
hist(data$area)
data$FFMC=data$FFMC^13
data=data[-which.max(data$ISI),]
data=data[,-12]
summary(data)


```

```{r}
#give numbers to categorical variables
num.data=data
num.data$month=gsub('jan', 1, num.data$month)
num.data$month=gsub('feb', 2, num.data$month)
num.data$month=gsub('mar', 3, num.data$month)
num.data$month=gsub('apr', 4, num.data$month)
num.data$month=gsub('may', 5, num.data$month)
num.data$month=gsub('jun', 6, num.data$month)
num.data$month=gsub('jul', 7, num.data$month)
num.data$month=gsub('aug', 8, num.data$month)
num.data$month=gsub('sep', 9, num.data$month)
num.data$month=gsub('oct', 10, num.data$month)
num.data$month=gsub('nov', 11, num.data$month)
num.data$month=gsub('dec', 12, num.data$month)
num.data$day=gsub('mon', 1, num.data$day)
num.data$day=gsub('tue', 2, num.data$day)
num.data$day=gsub('wed', 3, num.data$day)
num.data$day=gsub('thu', 4, num.data$day)
num.data$day=gsub('fri', 5, num.data$day)
num.data$day=gsub('sat', 6, num.data$day)
num.data$day=gsub('sun', 7, num.data$day)

num.data$day=as.numeric(num.data$day)
num.data$month=as.numeric(num.data$month)

num.cor=cor(num.data)
corrplot(num.cor, method = 'ellipse')

pairs(num.data)
```

```{r}
#make binary variables for categorical data
jan=rep(0,516)
feb=rep(0,516)
mar=rep(0,516)
apr=rep(0,516)
may=rep(0,516)
jun=rep(0,516)
jul=rep(0,516)
aug=rep(0,516)
sep=rep(0,516)
oct=rep(0,516)
nov=rep(0,516)
dec=rep(0,516)
for(i in 1:516){
  if(data$month[i]=='jan'){jan[i]=1}
  else if(data$month[i]=='feb'){feb[i]=1}
  else if(data$month[i]=='mar'){mar[i]=1}
  else if(data$month[i]=='apr'){apr[i]=1}
  else if(data$month[i]=='may'){may[i]=1}
  else if(data$month[i]=='jun'){jun[i]=1}
  else if(data$month[i]=='jul'){jul[i]=1}
  else if(data$month[i]=='aug'){aug[i]=1}
  else if(data$month[i]=='sep'){sep[i]=1}
  else if(data$month[i]=='oct'){oct[i]=1}
  else if(data$month[i]=='nov'){nov[i]=1}
  else if(data$month[i]=='dec'){dec[i]=1}
}

mon=rep(0,516)
tue=rep(0,516)
wed=rep(0,516)
thu=rep(0,516)
fri=rep(0,516)
sat=rep(0,516)
sun=rep(0,516)

for(i in 1:516){
  if(data$day[i]=='mon'){mon[i]=1}
  else if(data$day[i]=='tue'){tue[i]=1}
  else if(data$day[i]=='wed'){wed[i]=1}
  else if(data$day[i]=='thu'){thu[i]=1}
  else if(data$day[i]=='fri'){fri[i]=1}
  else if(data$day[i]=='sat'){sat[i]=1}
  else if(data$day[i]=='sun'){sun[i]=1}
}

data=data[,-(3:4)]
data=data.frame(data[,1:10], jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec,mon,tue,wed,thu,fri,sat,sun)
```


```{r}
train=sample(1:516,344)

#try model selection methods
min.model=glm(area~1, data=data[train,])
biggest=formula(glm(area~., data=data[train,]))
fwd.model=step(min.model, direction = 'forward', scope=biggest)
summary(fwd.model)

full.model=glm(area~.,data=data[train,])
back.model=step(full.model, direction='backward', trace=T)
summary(back.model)

#original MSE
test=data[-train,]
fwd.pred=predict(fwd.model, newdata=test)
fwd.mse=mean((fwd.pred-test$area)^2)
fwd.mse
back.pred=predict(back.model, newdata=test)
back.mse=mean((back.pred-test$area)^2)
back.mse

#k-fold cross validation
glm.fit.1=glm(area~dec+DMC+X+sep, data=data)
cv.err.1=cv.glm(data,glm.fit.1)
cv.err.1

glm.fit.2=glm(area~X + DMC + temp + jan + feb + mar + apr + jun + jul + aug + sep + oct, data=data)
cv.err.2=cv.glm(data,glm.fit.2)
cv.err.2
```


```{r}
bag.area=randomForest(area~., data=data[train,], mtry=6, importance=TRUE)
area.pred=predict(bag.area, newdata=data[-train,])
test.data=data[-train,]$area
plot(area.pred, test.data)
abline(0,1)
mean((area.pred-test.data)^2) #1.943381 in the same range as before

#my models so far are crap. again lol.

importance(bag.area)
varImpPlot(bag.area)
```

```{r}
#reclassify data
clus=data
clus$FFMC=exp(clus$FFMC)
clus$area=exp(clus$area)-1
#for(i in 1:517){
  #if(clus$area[i]==0){clus$area[i]='low'}
  #else if (clus$area[i]<=20){clus$area[i]='medium'}
  #else if (clus$area[i]<50){clus$area[i]='high'}
  #else (clus$area[i]='super high')
#}

```

```{r}
#SVM
```

```{r}
#KNN
test=clus[-train,]

folds=function(x){
  knn.fire=knn(clus[train,c(4,5)], test[,c(4,5)], clus[train,]$area, k=x)
  least=mean(knn.fire==test$area)

  knn.fire=knn(clus[train,c(4,7)], test[,c(4,7)], clus[train,]$area, k=x)
  a=mean(knn.fire==test$area)
  if(a>least){least=a}

  knn.fire=knn(clus[train,c(4,8)], test[,c(4,8)], clus[train,]$area, k=x)
  a=mean(knn.fire==test$area)
  if(a>least){least=a}

  knn.fire=knn(clus[train,c(4,19)], test[,c(4,19)], clus[train,]$area, k=x)
  a=mean(knn.fire==test$area)
  if(a>least){least=a}

  knn.fire=knn(clus[train,c(4,22)], test[,c(4,22)], clus[train,]$area, k=x)
  a=mean(knn.fire==test$area)
  if(a>least){least=a}

  knn.fire=knn(clus[train,c(5,7)], test[,c(5,7)], clus[train,]$area, k=x)
  a=mean(knn.fire==test$area)
  if(a>least){least=a}

  knn.fire=knn(clus[train,c(5,8)], test[,c(5,8)], clus[train,]$area, k=x)
  a=mean(knn.fire==test$area)
  if(a>least){least=a}

  knn.fire=knn(clus[train,c(5,19)], test[,c(5,19)], clus[train,]$area, k=x)
  a=mean(knn.fire==test$area)
  if(a>least){least=a}

  knn.fire=knn(clus[train,c(5,22)], test[,c(5,22)], clus[train,]$area, k=x)
  a=mean(knn.fire==test$area)
  if(a>least){least=a}

  knn.fire=knn(clus[train,c(7,8)], test[,c(7,8)], clus[train,]$area, k=x)
  a=mean(knn.fire==test$area)
  if(a>least){least=a}

  knn.fire=knn(clus[train,c(7,19)], test[,c(7,19)], clus[train,]$area, k=x)
  a=mean(knn.fire==test$area)
  if(a>least){least=a}

  knn.fire=knn(clus[train,c(7,22)], test[,c(7,22)], clus[train,]$area, k=x)
  a=mean(knn.fire==test$area)
  if(a>least){least=a}

  knn.fire=knn(clus[train,c(8,19)], test[,c(8,19)], clus[train,]$area, k=x)
  a=mean(knn.fire==test$area)
  if(a>least){least=a}

  knn.fire=knn(clus[train,c(8,22)], test[,c(8,22)], clus[train,]$area, k=x)
  a=mean(knn.fire==test$area)
  if(a>least){least=a}

  knn.fire=knn(clus[train,c(19,22)], test[,c(19,22)], clus[train,]$area, k=x)
  a=mean(knn.fire==test$area)
  if(a>least){least=a}
  
  return(least)
}

sapply(1:20, folds)
```

```{r}
#which combo of variables?
x=18

knn.fire=knn(clus[train,c(4,5)], test[,c(4,5)], clus[train,]$area, k=x)
mean(knn.fire==test$area)

knn.fire=knn(clus[train,c(4,7)], test[,c(4,7)], clus[train,]$area, k=x)
mean(knn.fire==test$area)

knn.fire=knn(clus[train,c(4,8)], test[,c(4,8)], clus[train,]$area, k=x)
mean(knn.fire==test$area)

knn.fire=knn(clus[train,c(4,19)], test[,c(4,19)], clus[train,]$area, k=x)
mean(knn.fire==test$area)

knn.fire=knn(clus[train,c(4,22)], test[,c(4,22)], clus[train,]$area, k=x)
mean(knn.fire==test$area)

knn.fire=knn(clus[train,c(5,7)], test[,c(5,7)], clus[train,]$area, k=x)
mean(knn.fire==test$area)

knn.fire=knn(clus[train,c(5,8)], test[,c(5,8)], clus[train,]$area, k=x)
mean(knn.fire==test$area)

knn.fire=knn(clus[train,c(5,19)], test[,c(5,19)], clus[train,]$area, k=x)
mean(knn.fire==test$area)

knn.fire=knn(clus[train,c(5,22)], test[,c(5,22)], clus[train,]$area, k=x)
mean(knn.fire==test$area)

knn.fire=knn(clus[train,c(7,8)], test[,c(7,8)], clus[train,]$area, k=x)
mean(knn.fire==test$area)

knn.fire=knn(clus[train,c(7,19)], test[,c(7,19)], clus[train,]$area, k=x)
mean(knn.fire==test$area)

knn.fire=knn(clus[train,c(7,22)], test[,c(7,22)], clus[train,]$area, k=x)
mean(knn.fire==test$area)

knn.fire=knn(clus[train,c(8,19)], test[,c(8,19)], clus[train,]$area, k=x)
mean(knn.fire==test$area)

knn.fire=knn(clus[train,c(8,22)], test[,c(8,22)], clus[train,]$area, k=x)
mean(knn.fire==test$area)

knn.fire=knn(clus[train,c(19,22)], test[,c(19,22)], clus[train,]$area, k=x)
mean(knn.fire==test$area)
```












